separate out ybox-pkg commands that don't require state.db vs those that do
- separation of the commands that don't require state.db like list, info etc avoids
  locking the database while they are running; the calling point in pkg.py sets a default
  flag for the same (needs_state=True) which is unset for these commands so that the
  calling point can either lock the db and pass them the state object, or can skip it
- cleanly deal with failures in subprocess run in run-user-bash-cmd
- wait after sending SIGTERM to subprocesses in entrypoint.sh only if it was
  successfully sent to at least one process
- don't try to overwrite pip.conf in entrypoint-user.sh if it already exists
- deal with possible absence of pyenv in pyenv/activate (e.g. in some containers)

diff --git a/src/ybox/conf/resources/run-user-bash-cmd b/src/ybox/conf/resources/run-user-bash-cmd
--- a/src/ybox/conf/resources/run-user-bash-cmd
+++ b/src/ybox/conf/resources/run-user-bash-cmd
@@ -8,7 +8,15 @@ if [ "$#" -ne 1 ]; then
 fi
 
 if [ "$(id -u)" -eq 0 -a -n "$YBOX_HOST_UID" ] && getent passwd $YBOX_HOST_UID > /dev/null; then
-  exec sudo -u "#$YBOX_HOST_UID" -g "#$YBOX_HOST_GID" /bin/bash -c "$1"
+  if ! sudo -u "#$YBOX_HOST_UID" -g "#$YBOX_HOST_GID" /bin/bash -c "$1"; then
+    status=$?
+    echo "FAILED in sudo execution of: $1"
+    exit $status
+  fi
 else
-  eval "$1"
+  if ! eval "$1"; then
+    status=$?
+    echo "FAILED in execution of: $1"
+    exit $status
+  fi
 fi
