fixed exit code handling in run-user-bash-cmd
exit code gets reset after the "if" statement, so store it first and then check the code

diff --git a/src/ybox/conf/resources/run-user-bash-cmd b/src/ybox/conf/resources/run-user-bash-cmd
--- a/src/ybox/conf/resources/run-user-bash-cmd
+++ b/src/ybox/conf/resources/run-user-bash-cmd
@@ -8,15 +8,17 @@ if [ "$#" -ne 1 ]; then
 fi
 
 if [ "$(id -u)" -eq 0 -a -n "$YBOX_HOST_UID" ] && getent passwd $YBOX_HOST_UID > /dev/null; then
-  if ! sudo -u "#$YBOX_HOST_UID" -g "#$YBOX_HOST_GID" /bin/bash -c "$1"; then
-    status=$?
-    echo "FAILED in sudo execution of: $1"
+  sudo -u "#$YBOX_HOST_UID" -g "#$YBOX_HOST_GID" /bin/bash -c "$1"
+  status=$?
+  if [ $status -ne 0 ]; then
+    echo "FAILED (exit code = $status) in sudo execution of: $1"
     exit $status
   fi
 else
-  if ! eval "$1"; then
-    status=$?
-    echo "FAILED in execution of: $1"
+  eval "$1"
+  status=$?
+  if [ $status -ne 0 ]; then
+    echo "FAILED (exit code = $status) in execution of: $1"
     exit $status
   fi
 fi
